/**
 * Stock Universe for QuantToGo MCP Server (github.com/QuantToGo/quanttogo-mcp)
 * Covers 62 stocks across 4 key markets:
 * - Singapore: Full STI 30 (SGX)
 * - China: 10 CSI 300 Leaders (SSE / SZSE)
 * - Hong Kong: 10 Hang Seng Leaders (HKEX)
 * - United States: 12 S&P 500 / Dow Jones Leaders (NYSE / NASDAQ)
 *
 * Linked with QuantToGo systematic alpha strategies.
 */

import { QuantToGoStockDefinition, QuantToGoStrategyDefinition } from './types.ts';

export const QUANTTOGO_STRATEGIES: QuantToGoStrategyDefinition[] = [
  {
    id: 'cnh_spread_flow',
    name: 'China Capital Flow (USD/CNH Spread Macro)',
    market: 'China',
    description:
      'Monitors offshore RMB (CNH) vs onshore RMB (CNY) spread and PBOC fixing divergence to predict cross-border institutional capital flows into A-Shares.',
    cagr: 24.8,
    sharpe: 1.62,
    maxDrawdown: -14.2,
    winRate: 64.5,
    benchmark: 'CSI 300 Index',
    currentSignal: 'BUY',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: '70% CSI 300 / 30% Cash',
    targetTickers: ['600519', '000858', '601318', '600036'],
    rationale: 'USD/CNH spread narrowing below 80 bps indicates accelerating northbound capital flow inflows.',
  },
  {
    id: 'ashare_size_rotation',
    name: 'A-Share Size Rotation (Large vs Small Cap)',
    market: 'China',
    description:
      'Dynamic factor rotation between mega-cap CSI 300 quality value and high-beta CSI 1000 growth based on market breadth and credit impulse.',
    cagr: 28.4,
    sharpe: 1.54,
    maxDrawdown: -18.6,
    winRate: 59.2,
    benchmark: 'CSI 300 Index',
    currentSignal: 'BUY',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: 'Overweight Large-Cap Quality Value',
    targetTickers: ['601857', '600900', '002594'],
    rationale: 'Liquidity tightening regime favors low-beta dividend champions and mega-cap SOEs.',
  },
  {
    id: 'ashare_limitdown_exhaustion',
    name: 'A-Share Limit-Down Capitulation Reversal',
    market: 'China',
    description:
      'Detects extreme selling climaxes when market-wide limit-down stocks exceed statistical thresholds, identifying high-probability V-bottoms.',
    cagr: 31.2,
    sharpe: 1.78,
    maxDrawdown: -12.1,
    winRate: 72.0,
    benchmark: 'CSI 300 Index',
    currentSignal: 'NEUTRAL',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: 'Cash / Defensive Hold',
    targetTickers: ['000333', '600276'],
    rationale: 'Daily limit-down count normal (under 5 stocks). No capitulation panic trigger active.',
  },
  {
    id: 'tqqq_vix_dip',
    name: 'US Tech 3x TQQQ VIX Dip Accumulator',
    market: 'US',
    description:
      'Quantifies extreme fear spikes in the VIX term structure and CBOE put/call ratios to execute dip-buying in leveraged Nasdaq-100 (TQQQ).',
    cagr: 42.6,
    sharpe: 1.48,
    maxDrawdown: -26.5,
    winRate: 68.4,
    benchmark: 'Nasdaq 100',
    currentSignal: 'BUY',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: '35% TQQQ / 65% Cash & Short-Term Treasuries',
    targetTickers: ['AAPL', 'MSFT', 'NVDA', 'AMZN', 'GOOGL', 'META'],
    rationale: 'VIX 9-day to 30-day backwardation cleared; 50-DMA mean-reversion dip entry triggered.',
  },
  {
    id: 'nasdaq_trend_filter',
    name: 'Trend-Filtered 3x Nasdaq 100 Allocation',
    market: 'US',
    description:
      'Regime-switching trend model that steps into 3x Nasdaq leverage during bullish price regimes and parks in US Dollar cash during distribution phases.',
    cagr: 36.5,
    sharpe: 1.58,
    maxDrawdown: -19.4,
    winRate: 61.8,
    benchmark: 'Nasdaq 100',
    currentSignal: 'BUY',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: '100% Equity Exposure',
    targetTickers: ['NVDA', 'MSFT', 'TSLA', 'AMZN'],
    rationale: 'Nasdaq 100 trading securely above rising 50-day and 200-day moving averages with strong volume.',
  },
  {
    id: 'retail_sentiment_reversal',
    name: 'Contrarian Retail Sentiment Reversal',
    market: 'US',
    description:
      'Fades extreme retail greed and panic indicators across social, options volume, and margin debt balances.',
    cagr: 22.1,
    sharpe: 1.35,
    maxDrawdown: -13.8,
    winRate: 66.2,
    benchmark: 'S&P 500',
    currentSignal: 'NEUTRAL',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: 'Equal-Weight Core Holdings',
    targetTickers: ['JPM', 'XOM', 'PG', 'COST', 'WMT'],
    rationale: 'Sentiment index at 54/100 (Neutral zone). Hold current portfolio weights.',
  },
  {
    id: 'singapore_dividend_value',
    name: 'Singapore STI High-Yield Flow Momentum',
    market: 'Singapore',
    description:
      'Systematic allocation across Straits Times Index top dividend champions, banking majors (DBS, OCBC, UOB), and defensive infrastructure REITs.',
    cagr: 16.8,
    sharpe: 1.82,
    maxDrawdown: -8.9,
    winRate: 74.5,
    benchmark: 'Straits Times Index (STI)',
    currentSignal: 'BUY',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: '80% STI Blue Chips / 20% SGD Cash',
    targetTickers: ['D05', 'O39', 'U11', 'Z74'],
    rationale: 'Average dividend yield of 5.3% provides strong asymmetric buffer while banking NIMs remain stable.',
  },
  {
    id: 'hangseng_tech_arbitrage',
    name: 'Hang Seng Tech / Dual-Listing Arbitrage',
    market: 'Hong Kong',
    description:
      'Systematic quantitative valuation mean-reversion for Hong Kong tech giants against their US ADR counterparts and relative sector averages.',
    cagr: 27.5,
    sharpe: 1.42,
    maxDrawdown: -22.4,
    winRate: 58.7,
    benchmark: 'Hang Seng Tech Index',
    currentSignal: 'BUY',
    signalDate: new Date().toISOString().slice(0, 10),
    recommendedAllocation: 'Overweight Tencent, Alibaba & Meituan',
    targetTickers: ['0700', '9988', '3690', '9618'],
    rationale: 'HKEX Tech forward P/E at 15.2x represents a 35% discount to 5-year historical multiples.',
  },
];

export const QUANTTOGO_STOCK_UNIVERSE: QuantToGoStockDefinition[] = [
  // ==========================================
  // SINGAPORE (STI 30 Constituents - 30 Stocks)
  // ==========================================
  {
    ticker: 'D05',
    name: 'DBS Group Holdings Ltd',
    quantToGoSymbol: 'SGX:D05',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Financial Services',
    price: 36.42,
    change: 0.38,
    changePercent: 1.05,
    ma50: 35.80,
    currentVolume: 4250000,
    weeklyAvgVolume: 3800000,
    pe: 11.2,
    low52w: 30.12,
    high52w: 37.10,
    marketCap: 'S$93.2B',
    dividendYield: 5.8,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'O39',
    name: 'Oversea-Chinese Banking Corp Ltd',
    quantToGoSymbol: 'SGX:O39',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Financial Services',
    price: 14.88,
    change: -0.06,
    changePercent: -0.4,
    ma50: 15.10,
    currentVolume: 5120000,
    weeklyAvgVolume: 4300000,
    pe: 10.4,
    low52w: 12.45,
    high52w: 15.65,
    marketCap: 'S$66.9B',
    dividendYield: 5.9,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'U11',
    name: 'United Overseas Bank Ltd',
    quantToGoSymbol: 'SGX:U11',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Financial Services',
    price: 31.75,
    change: 0.15,
    changePercent: 0.47,
    ma50: 30.90,
    currentVolume: 2150000,
    weeklyAvgVolume: 1950000,
    pe: 10.1,
    low52w: 26.80,
    high52w: 32.50,
    marketCap: 'S$53.1B',
    dividendYield: 5.5,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'Z74',
    name: 'Singapore Telecommunications Ltd',
    quantToGoSymbol: 'SGX:Z74',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Communication Services',
    price: 3.18,
    change: 0.02,
    changePercent: 0.63,
    ma50: 3.05,
    currentVolume: 28400000,
    weeklyAvgVolume: 24100000,
    pe: 18.5,
    low52w: 2.31,
    high52w: 3.32,
    marketCap: 'S$52.5B',
    dividendYield: 4.8,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'C6L',
    name: 'Singapore Airlines Ltd',
    quantToGoSymbol: 'SGX:C6L',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Industrials',
    price: 6.45,
    change: -0.05,
    changePercent: -0.77,
    ma50: 6.62,
    currentVolume: 7800000,
    weeklyAvgVolume: 8200000,
    pe: 7.2,
    low52w: 6.10,
    high52w: 7.61,
    marketCap: 'S$19.2B',
    dividendYield: 5.8,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'BN4',
    name: 'Keppel Ltd',
    quantToGoSymbol: 'SGX:BN4',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Industrials',
    price: 6.55,
    change: 0.08,
    changePercent: 1.24,
    ma50: 6.42,
    currentVolume: 4100000,
    weeklyAvgVolume: 3600000,
    pe: 12.8,
    low52w: 5.88,
    high52w: 7.50,
    marketCap: 'S$11.6B',
    dividendYield: 5.2,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'S68',
    name: 'Singapore Exchange Ltd',
    quantToGoSymbol: 'SGX:S68',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Financial Services',
    price: 11.20,
    change: 0.14,
    changePercent: 1.27,
    ma50: 10.45,
    currentVolume: 3200000,
    weeklyAvgVolume: 2500000,
    pe: 22.4,
    low52w: 8.92,
    high52w: 11.50,
    marketCap: 'S$12.0B',
    dividendYield: 3.1,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'G13',
    name: 'Genting Singapore Ltd',
    quantToGoSymbol: 'SGX:G13',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Consumer Cyclical',
    price: 0.83,
    change: -0.01,
    changePercent: -1.19,
    ma50: 0.86,
    currentVolume: 16500000,
    weeklyAvgVolume: 18200000,
    pe: 15.6,
    low52w: 0.80,
    high52w: 1.06,
    marketCap: 'S$10.0B',
    dividendYield: 4.8,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'F34',
    name: 'Wilmar International Ltd',
    quantToGoSymbol: 'SGX:F34',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Consumer Defensive',
    price: 3.12,
    change: 0.01,
    changePercent: 0.32,
    ma50: 3.16,
    currentVolume: 6100000,
    weeklyAvgVolume: 5800000,
    pe: 11.8,
    low52w: 2.95,
    high52w: 3.88,
    marketCap: 'S$19.5B',
    dividendYield: 5.4,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'C38U',
    name: 'CapitaLand Integrated Commercial Trust',
    quantToGoSymbol: 'SGX:C38U',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 2.05,
    change: 0.02,
    changePercent: 0.99,
    ma50: 2.01,
    currentVolume: 14200000,
    weeklyAvgVolume: 12800000,
    pe: 16.2,
    low52w: 1.78,
    high52w: 2.15,
    marketCap: 'S$13.8B',
    dividendYield: 5.2,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'A17U',
    name: 'CapitaLand Ascendas REIT',
    quantToGoSymbol: 'SGX:A17U',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 2.82,
    change: 0.01,
    changePercent: 0.36,
    ma50: 2.76,
    currentVolume: 9200000,
    weeklyAvgVolume: 8500000,
    pe: 17.5,
    low52w: 2.50,
    high52w: 2.98,
    marketCap: 'S$12.2B',
    dividendYield: 5.4,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'ME8U',
    name: 'Mapletree Industrial Trust',
    quantToGoSymbol: 'SGX:ME8U',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 2.38,
    change: 0.03,
    changePercent: 1.28,
    ma50: 2.30,
    currentVolume: 5600000,
    weeklyAvgVolume: 4900000,
    pe: 16.8,
    low52w: 2.10,
    high52w: 2.52,
    marketCap: 'S$6.7B',
    dividendYield: 5.6,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'M44U',
    name: 'Mapletree Logistics Trust',
    quantToGoSymbol: 'SGX:M44U',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 1.42,
    change: -0.01,
    changePercent: -0.7,
    ma50: 1.46,
    currentVolume: 11200000,
    weeklyAvgVolume: 10400000,
    pe: 15.4,
    low52w: 1.28,
    high52w: 1.74,
    marketCap: 'S$7.1B',
    dividendYield: 6.2,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'N2IU',
    name: 'Mapletree Pan Asia Commercial Trust',
    quantToGoSymbol: 'SGX:N2IU',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 1.34,
    change: 0.01,
    changePercent: 0.75,
    ma50: 1.31,
    currentVolume: 7400000,
    weeklyAvgVolume: 6900000,
    pe: 14.2,
    low52w: 1.16,
    high52w: 1.58,
    marketCap: 'S$7.0B',
    dividendYield: 6.5,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'C09',
    name: 'City Developments Ltd',
    quantToGoSymbol: 'SGX:C09',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 5.48,
    change: -0.04,
    changePercent: -0.72,
    ma50: 5.65,
    currentVolume: 2400000,
    weeklyAvgVolume: 2100000,
    pe: 14.8,
    low52w: 5.25,
    high52w: 7.12,
    marketCap: 'S$4.9B',
    dividendYield: 3.8,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'U96',
    name: 'Sembcorp Industries Ltd',
    quantToGoSymbol: 'SGX:U96',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Utilities',
    price: 5.24,
    change: 0.06,
    changePercent: 1.16,
    ma50: 5.08,
    currentVolume: 4600000,
    weeklyAvgVolume: 3900000,
    pe: 10.6,
    low52w: 4.45,
    high52w: 5.88,
    marketCap: 'S$9.3B',
    dividendYield: 3.5,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'S63',
    name: 'Singapore Technologies Engineering Ltd',
    quantToGoSymbol: 'SGX:S63',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Industrials',
    price: 4.62,
    change: 0.04,
    changePercent: 0.87,
    ma50: 4.48,
    currentVolume: 3800000,
    weeklyAvgVolume: 3400000,
    pe: 23.5,
    low52w: 3.65,
    high52w: 4.75,
    marketCap: 'S$14.4B',
    dividendYield: 3.5,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'Y92',
    name: 'Thai Beverage PCL',
    quantToGoSymbol: 'SGX:Y92',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Consumer Defensive',
    price: 0.52,
    change: 0.00,
    changePercent: 0.0,
    ma50: 0.51,
    currentVolume: 22100000,
    weeklyAvgVolume: 19800000,
    pe: 12.4,
    low52w: 0.46,
    high52w: 0.60,
    marketCap: 'S$13.1B',
    dividendYield: 4.8,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'J36',
    name: 'Jardine Matheson Holdings Ltd',
    quantToGoSymbol: 'SGX:J36',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'USD',
    sector: 'Industrials',
    price: 38.60,
    change: -0.40,
    changePercent: -1.02,
    ma50: 39.80,
    currentVolume: 420000,
    weeklyAvgVolume: 390000,
    pe: 8.8,
    low52w: 35.10,
    high52w: 48.50,
    marketCap: '$11.2B',
    dividendYield: 5.6,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'J37',
    name: 'Jardine Cycle & Carriage Ltd',
    quantToGoSymbol: 'SGX:J37',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Consumer Cyclical',
    price: 27.20,
    change: 0.35,
    changePercent: 1.3,
    ma50: 26.50,
    currentVolume: 380000,
    weeklyAvgVolume: 310000,
    pe: 8.2,
    low52w: 24.10,
    high52w: 34.20,
    marketCap: 'S$10.7B',
    dividendYield: 5.9,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'D01',
    name: 'DFI Retail Group Holdings Ltd',
    quantToGoSymbol: 'SGX:D01',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'USD',
    sector: 'Consumer Defensive',
    price: 2.14,
    change: -0.02,
    changePercent: -0.93,
    ma50: 2.18,
    currentVolume: 1200000,
    weeklyAvgVolume: 1100000,
    pe: 18.2,
    low52w: 1.82,
    high52w: 2.65,
    marketCap: '$2.9B',
    dividendYield: 3.8,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'H78',
    name: 'Hongkong Land Holdings Ltd',
    quantToGoSymbol: 'SGX:H78',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'USD',
    sector: 'Real Estate',
    price: 4.12,
    change: 0.08,
    changePercent: 1.98,
    ma50: 3.85,
    currentVolume: 2800000,
    weeklyAvgVolume: 2100000,
    pe: 12.5,
    low52w: 3.05,
    high52w: 4.30,
    marketCap: '$9.1B',
    dividendYield: 5.3,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'V03',
    name: 'Venture Corp Ltd',
    quantToGoSymbol: 'SGX:V03',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Technology',
    price: 13.85,
    change: -0.15,
    changePercent: -1.07,
    ma50: 14.30,
    currentVolume: 820000,
    weeklyAvgVolume: 790000,
    pe: 14.5,
    low52w: 12.80,
    high52w: 16.10,
    marketCap: 'S$4.0B',
    dividendYield: 5.4,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'K71U',
    name: 'Keppel REIT',
    quantToGoSymbol: 'SGX:K71U',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 0.94,
    change: 0.01,
    changePercent: 1.08,
    ma50: 0.92,
    currentVolume: 8900000,
    weeklyAvgVolume: 7800000,
    pe: 15.1,
    low52w: 0.81,
    high52w: 0.99,
    marketCap: 'S$3.6B',
    dividendYield: 6.2,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'AJBU',
    name: 'Keppel DC REIT',
    quantToGoSymbol: 'SGX:AJBU',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 2.22,
    change: 0.04,
    changePercent: 1.83,
    ma50: 2.05,
    currentVolume: 6700000,
    weeklyAvgVolume: 5100000,
    pe: 21.8,
    low52w: 1.62,
    high52w: 2.28,
    marketCap: 'S$3.9B',
    dividendYield: 4.4,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'BUOU',
    name: 'Frasers Logistics & Commercial Trust',
    quantToGoSymbol: 'SGX:BUOU',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 1.10,
    change: -0.01,
    changePercent: -0.9,
    ma50: 1.12,
    currentVolume: 9400000,
    weeklyAvgVolume: 8900000,
    pe: 14.8,
    low52w: 0.98,
    high52w: 1.25,
    marketCap: 'S$4.1B',
    dividendYield: 6.4,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'J69U',
    name: 'Frasers Centrepoint Trust',
    quantToGoSymbol: 'SGX:J69U',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 2.32,
    change: 0.02,
    changePercent: 0.87,
    ma50: 2.28,
    currentVolume: 4200000,
    weeklyAvgVolume: 3800000,
    pe: 16.5,
    low52w: 2.05,
    high52w: 2.42,
    marketCap: 'S$4.0B',
    dividendYield: 5.2,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'O5RU',
    name: 'AIMS APAC REIT',
    quantToGoSymbol: 'SGX:O5RU',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 1.35,
    change: 0.01,
    changePercent: 0.75,
    ma50: 1.33,
    currentVolume: 2100000,
    weeklyAvgVolume: 1900000,
    pe: 13.9,
    low52w: 1.21,
    high52w: 1.42,
    marketCap: 'S$1.1B',
    dividendYield: 6.9,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'U10',
    name: 'UOL Group Ltd',
    quantToGoSymbol: 'SGX:U10',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Real Estate',
    price: 5.58,
    change: -0.03,
    changePercent: -0.53,
    ma50: 5.72,
    currentVolume: 1400000,
    weeklyAvgVolume: 1300000,
    pe: 13.2,
    low52w: 5.15,
    high52w: 6.85,
    marketCap: 'S$4.7B',
    dividendYield: 3.6,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'S58',
    name: 'SATS Ltd',
    quantToGoSymbol: 'SGX:S58',
    exchange: 'SGX',
    market: 'Singapore',
    currency: 'SGD',
    sector: 'Industrials',
    price: 3.75,
    change: 0.07,
    changePercent: 1.9,
    ma50: 3.48,
    currentVolume: 8200000,
    weeklyAvgVolume: 6400000,
    pe: 34.2,
    low52w: 2.45,
    high52w: 3.92,
    marketCap: 'S$5.6B',
    dividendYield: 1.2,
    quantToGoStrategyId: 'singapore_dividend_value',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },

  // ==========================================
  // CHINA (CSI 300 Leaders - 10 Stocks)
  // ==========================================
  {
    ticker: '600519',
    name: 'Kweichow Moutai Co Ltd',
    quantToGoSymbol: 'SHA:600519',
    exchange: 'SHA',
    market: 'China',
    currency: 'CNY',
    sector: 'Consumer Defensive',
    price: 1548.0,
    change: 18.5,
    changePercent: 1.21,
    ma50: 1495.0,
    currentVolume: 4200000,
    weeklyAvgVolume: 3240000,
    pe: 24.5,
    low52w: 1245.0,
    high52w: 1820.0,
    marketCap: '¥1.94T',
    dividendYield: 3.2,
    quantToGoStrategyId: 'cnh_spread_flow',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '300750',
    name: 'Contemporary Amperex Technology Co Ltd',
    quantToGoSymbol: 'SHE:300750',
    exchange: 'SHE',
    market: 'China',
    currency: 'CNY',
    sector: 'Industrials',
    price: 258.4,
    change: 4.8,
    changePercent: 1.89,
    ma50: 236.2,
    currentVolume: 31200000,
    weeklyAvgVolume: 24500000,
    pe: 21.6,
    low52w: 140.2,
    high52w: 285.0,
    marketCap: '¥1.14T',
    dividendYield: 1.8,
    quantToGoStrategyId: 'cnh_spread_flow',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '601318',
    name: 'Ping An Insurance Group Co of China Ltd',
    quantToGoSymbol: 'SHA:601318',
    exchange: 'SHA',
    market: 'China',
    currency: 'CNY',
    sector: 'Financial Services',
    price: 54.2,
    change: -0.6,
    changePercent: -1.09,
    ma50: 51.8,
    currentVolume: 68400000,
    weeklyAvgVolume: 62000000,
    pe: 9.8,
    low52w: 37.8,
    high52w: 62.5,
    marketCap: '¥988B',
    dividendYield: 4.5,
    quantToGoStrategyId: 'cnh_spread_flow',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '600036',
    name: 'China Merchants Bank Co Ltd',
    quantToGoSymbol: 'SHA:600036',
    exchange: 'SHA',
    market: 'China',
    currency: 'CNY',
    sector: 'Financial Services',
    price: 38.45,
    change: 0.25,
    changePercent: 0.65,
    ma50: 36.9,
    currentVolume: 42100000,
    weeklyAvgVolume: 38900000,
    pe: 6.4,
    low52w: 27.4,
    high52w: 41.2,
    marketCap: '¥970B',
    dividendYield: 5.1,
    quantToGoStrategyId: 'cnh_spread_flow',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '002594',
    name: 'BYD Co Ltd',
    quantToGoSymbol: 'SHE:002594',
    exchange: 'SHE',
    market: 'China',
    currency: 'CNY',
    sector: 'Consumer Cyclical',
    price: 298.5,
    change: 6.2,
    changePercent: 2.12,
    ma50: 275.0,
    currentVolume: 19800000,
    weeklyAvgVolume: 15400000,
    pe: 22.8,
    low52w: 165.0,
    high52w: 320.0,
    marketCap: '¥868B',
    dividendYield: 1.4,
    quantToGoStrategyId: 'ashare_size_rotation',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '601857',
    name: 'PetroChina Co Ltd',
    quantToGoSymbol: 'SHA:601857',
    exchange: 'SHA',
    market: 'China',
    currency: 'CNY',
    sector: 'Energy',
    price: 8.42,
    change: -0.05,
    changePercent: -0.59,
    ma50: 8.65,
    currentVolume: 74200000,
    weeklyAvgVolume: 81000000,
    pe: 9.2,
    low52w: 6.8,
    high52w: 10.8,
    marketCap: '¥1.54T',
    dividendYield: 5.6,
    quantToGoStrategyId: 'ashare_size_rotation',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '000858',
    name: 'Wuliangye Yibin Co Ltd',
    quantToGoSymbol: 'SHE:000858',
    exchange: 'SHE',
    market: 'China',
    currency: 'CNY',
    sector: 'Consumer Defensive',
    price: 152.0,
    change: 1.8,
    changePercent: 1.2,
    ma50: 144.5,
    currentVolume: 16500000,
    weeklyAvgVolume: 13800000,
    pe: 18.2,
    low52w: 112.0,
    high52w: 172.0,
    marketCap: '¥590B',
    dividendYield: 3.5,
    quantToGoStrategyId: 'cnh_spread_flow',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '600900',
    name: 'China Yangtze Power Co Ltd',
    quantToGoSymbol: 'SHA:600900',
    exchange: 'SHA',
    market: 'China',
    currency: 'CNY',
    sector: 'Utilities',
    price: 28.95,
    change: 0.15,
    changePercent: 0.52,
    ma50: 29.8,
    currentVolume: 32000000,
    weeklyAvgVolume: 34500000,
    pe: 20.4,
    low52w: 22.8,
    high52w: 31.4,
    marketCap: '¥708B',
    dividendYield: 3.4,
    quantToGoStrategyId: 'ashare_size_rotation',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '000333',
    name: 'Midea Group Co Ltd',
    quantToGoSymbol: 'SHE:000333',
    exchange: 'SHE',
    market: 'China',
    currency: 'CNY',
    sector: 'Consumer Cyclical',
    price: 74.2,
    change: 0.9,
    changePercent: 1.23,
    ma50: 69.5,
    currentVolume: 24500000,
    weeklyAvgVolume: 21000000,
    pe: 14.8,
    low52w: 52.0,
    high52w: 80.5,
    marketCap: '¥568B',
    dividendYield: 4.1,
    quantToGoStrategyId: 'ashare_limitdown_exhaustion',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '600276',
    name: 'Jiangsu Hengrui Pharmaceuticals Co Ltd',
    quantToGoSymbol: 'SHA:600276',
    exchange: 'SHA',
    market: 'China',
    currency: 'CNY',
    sector: 'Healthcare',
    price: 49.8,
    change: -0.4,
    changePercent: -0.8,
    ma50: 47.2,
    currentVolume: 18200000,
    weeklyAvgVolume: 16500000,
    pe: 54.2,
    low52w: 38.0,
    high52w: 55.6,
    marketCap: '¥318B',
    dividendYield: 0.8,
    quantToGoStrategyId: 'ashare_limitdown_exhaustion',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },

  // ==========================================
  // HONG KONG (Hang Seng Leaders - 10 Stocks)
  // ==========================================
  {
    ticker: '0700',
    name: 'Tencent Holdings Ltd',
    quantToGoSymbol: 'HKG:0700',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Communication Services',
    price: 418.2,
    change: 6.4,
    changePercent: 1.55,
    ma50: 402.5,
    currentVolume: 18900000,
    weeklyAvgVolume: 16000000,
    pe: 22.8,
    low52w: 260.0,
    high52w: 482.0,
    marketCap: 'HK$3.92T',
    dividendYield: 1.2,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '9988',
    name: 'Alibaba Group Holding Ltd',
    quantToGoSymbol: 'HKG:9988',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Consumer Cyclical',
    price: 98.45,
    change: -1.25,
    changePercent: -1.25,
    ma50: 92.8,
    currentVolume: 42100000,
    weeklyAvgVolume: 46500000,
    pe: 15.2,
    low52w: 68.0,
    high52w: 118.0,
    marketCap: 'HK$1.88T',
    dividendYield: 2.1,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '3690',
    name: 'Meituan',
    quantToGoSymbol: 'HKG:3690',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Consumer Cyclical',
    price: 182.5,
    change: 4.2,
    changePercent: 2.36,
    ma50: 165.0,
    currentVolume: 28400000,
    weeklyAvgVolume: 22100000,
    pe: 28.5,
    low52w: 61.5,
    high52w: 215.0,
    marketCap: 'HK$1.13T',
    dividendYield: 0.0,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '0941',
    name: 'China Mobile Ltd',
    quantToGoSymbol: 'HKG:0941',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Communication Services',
    price: 72.8,
    change: 0.35,
    changePercent: 0.48,
    ma50: 73.5,
    currentVolume: 12500000,
    weeklyAvgVolume: 14100000,
    pe: 10.4,
    low52w: 61.2,
    high52w: 78.5,
    marketCap: 'HK$1.55T',
    dividendYield: 6.8,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '0005',
    name: 'HSBC Holdings PLC',
    quantToGoSymbol: 'HKG:0005',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Financial Services',
    price: 68.9,
    change: 0.45,
    changePercent: 0.66,
    ma50: 67.2,
    currentVolume: 16800000,
    weeklyAvgVolume: 15200000,
    pe: 7.2,
    low52w: 57.5,
    high52w: 71.8,
    marketCap: 'HK$1.28T',
    dividendYield: 7.4,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '1299',
    name: 'AIA Group Ltd',
    quantToGoSymbol: 'HKG:1299',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Financial Services',
    price: 62.4,
    change: -0.8,
    changePercent: -1.27,
    ma50: 59.5,
    currentVolume: 24500000,
    weeklyAvgVolume: 22800000,
    pe: 14.2,
    low52w: 45.2,
    high52w: 74.0,
    marketCap: 'HK$698B',
    dividendYield: 2.8,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '0388',
    name: 'Hong Kong Exchanges & Clearing Ltd',
    quantToGoSymbol: 'HKG:0388',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Financial Services',
    price: 312.0,
    change: 5.6,
    changePercent: 1.83,
    ma50: 285.0,
    currentVolume: 6800000,
    weeklyAvgVolume: 5400000,
    pe: 32.4,
    low52w: 215.0,
    high52w: 395.0,
    marketCap: 'HK$395B',
    dividendYield: 2.9,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '9618',
    name: 'JD.com Inc',
    quantToGoSymbol: 'HKG:9618',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Consumer Cyclical',
    price: 154.2,
    change: -2.4,
    changePercent: -1.53,
    ma50: 146.5,
    currentVolume: 12400000,
    weeklyAvgVolume: 13800000,
    pe: 12.8,
    low52w: 86.0,
    high52w: 195.0,
    marketCap: 'HK$482B',
    dividendYield: 2.2,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '9888',
    name: 'Baidu Inc',
    quantToGoSymbol: 'HKG:9888',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Communication Services',
    price: 88.5,
    change: 0.6,
    changePercent: 0.68,
    ma50: 89.2,
    currentVolume: 5400000,
    weeklyAvgVolume: 6100000,
    pe: 11.4,
    low52w: 78.5,
    high52w: 122.0,
    marketCap: 'HK$248B',
    dividendYield: 0.0,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: '2318',
    name: 'Ping An Insurance Group (HK)',
    quantToGoSymbol: 'HKG:2318',
    exchange: 'HKEX',
    market: 'Hong Kong',
    currency: 'HKD',
    sector: 'Financial Services',
    price: 48.6,
    change: -0.35,
    changePercent: -0.72,
    ma50: 46.8,
    currentVolume: 34100000,
    weeklyAvgVolume: 38200000,
    pe: 8.5,
    low52w: 30.2,
    high52w: 58.0,
    marketCap: 'HK$882B',
    dividendYield: 5.6,
    quantToGoStrategyId: 'hangseng_tech_arbitrage',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },

  // ==========================================
  // UNITED STATES (S&P 500 / Big Tech Leaders - 12 Stocks)
  // ==========================================
  {
    ticker: 'AAPL',
    name: 'Apple Inc',
    quantToGoSymbol: 'NASDAQ:AAPL',
    exchange: 'NASDAQ',
    market: 'US',
    currency: 'USD',
    sector: 'Information Technology',
    price: 232.5,
    change: 1.8,
    changePercent: 0.78,
    ma50: 226.4,
    currentVolume: 48200000,
    weeklyAvgVolume: 43800000,
    pe: 34.8,
    low52w: 164.08,
    high52w: 237.23,
    marketCap: '$3.52T',
    dividendYield: 0.5,
    quantToGoStrategyId: 'tqqq_vix_dip',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft Corp',
    quantToGoSymbol: 'NASDAQ:MSFT',
    exchange: 'NASDAQ',
    market: 'US',
    currency: 'USD',
    sector: 'Information Technology',
    price: 428.2,
    change: 3.1,
    changePercent: 0.73,
    ma50: 420.5,
    currentVolume: 19800000,
    weeklyAvgVolume: 18200000,
    pe: 35.6,
    low52w: 309.45,
    high52w: 468.35,
    marketCap: '$3.18T',
    dividendYield: 0.8,
    quantToGoStrategyId: 'nasdaq_trend_filter',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corp',
    quantToGoSymbol: 'NASDAQ:NVDA',
    exchange: 'NASDAQ',
    market: 'US',
    currency: 'USD',
    sector: 'Information Technology',
    price: 138.25,
    change: 4.15,
    changePercent: 3.09,
    ma50: 122.8,
    currentVolume: 64200000,
    weeklyAvgVolume: 49500000,
    pe: 62.4,
    low52w: 39.23,
    high52w: 140.76,
    marketCap: '$3.39T',
    dividendYield: 0.1,
    quantToGoStrategyId: 'nasdaq_trend_filter',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'AMZN',
    name: 'Amazon.com Inc',
    quantToGoSymbol: 'NASDAQ:AMZN',
    exchange: 'NASDAQ',
    market: 'US',
    currency: 'USD',
    sector: 'Consumer Discretionary',
    price: 188.6,
    change: 1.4,
    changePercent: 0.75,
    ma50: 182.4,
    currentVolume: 34500000,
    weeklyAvgVolume: 32100000,
    pe: 43.8,
    low52w: 118.35,
    high52w: 201.2,
    marketCap: '$1.97T',
    dividendYield: 0.0,
    quantToGoStrategyId: 'tqqq_vix_dip',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet Inc Class A',
    quantToGoSymbol: 'NASDAQ:GOOGL',
    exchange: 'NASDAQ',
    market: 'US',
    currency: 'USD',
    sector: 'Communication Services',
    price: 165.4,
    change: -0.85,
    changePercent: -0.51,
    ma50: 168.2,
    currentVolume: 22400000,
    weeklyAvgVolume: 25100000,
    pe: 23.9,
    low52w: 120.21,
    high52w: 191.75,
    marketCap: '$2.04T',
    dividendYield: 0.5,
    quantToGoStrategyId: 'tqqq_vix_dip',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'META',
    name: 'Meta Platforms Inc',
    quantToGoSymbol: 'NASDAQ:META',
    exchange: 'NASDAQ',
    market: 'US',
    currency: 'USD',
    sector: 'Communication Services',
    price: 588.2,
    change: 7.4,
    changePercent: 1.27,
    ma50: 554.0,
    currentVolume: 12800000,
    weeklyAvgVolume: 10500000,
    pe: 28.5,
    low52w: 279.4,
    high52w: 602.95,
    marketCap: '$1.48T',
    dividendYield: 0.4,
    quantToGoStrategyId: 'tqqq_vix_dip',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'TSLA',
    name: 'Tesla Inc',
    quantToGoSymbol: 'NASDAQ:TSLA',
    exchange: 'NASDAQ',
    market: 'US',
    currency: 'USD',
    sector: 'Consumer Discretionary',
    price: 218.4,
    change: -4.8,
    changePercent: -2.15,
    ma50: 228.6,
    currentVolume: 68400000,
    weeklyAvgVolume: 74200000,
    pe: 64.2,
    low52w: 138.8,
    high52w: 271.0,
    marketCap: '$698B',
    dividendYield: 0.0,
    quantToGoStrategyId: 'nasdaq_trend_filter',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'JPM',
    name: 'JPMorgan Chase & Co',
    quantToGoSymbol: 'NYSE:JPM',
    exchange: 'NYSE',
    market: 'US',
    currency: 'USD',
    sector: 'Financial Services',
    price: 224.5,
    change: 1.8,
    changePercent: 0.81,
    ma50: 218.2,
    currentVolume: 8900000,
    weeklyAvgVolume: 8100000,
    pe: 12.6,
    low52w: 138.4,
    high52w: 228.4,
    marketCap: '$642B',
    dividendYield: 2.2,
    quantToGoStrategyId: 'retail_sentiment_reversal',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'V',
    name: 'Visa Inc',
    quantToGoSymbol: 'NYSE:V',
    exchange: 'NYSE',
    market: 'US',
    currency: 'USD',
    sector: 'Financial Services',
    price: 284.2,
    change: 1.1,
    changePercent: 0.39,
    ma50: 278.4,
    currentVolume: 5600000,
    weeklyAvgVolume: 5100000,
    pe: 29.8,
    low52w: 227.8,
    high52w: 293.0,
    marketCap: '$578B',
    dividendYield: 0.8,
    quantToGoStrategyId: 'retail_sentiment_reversal',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'UNH',
    name: 'UnitedHealth Group Inc',
    quantToGoSymbol: 'NYSE:UNH',
    exchange: 'NYSE',
    market: 'US',
    currency: 'USD',
    sector: 'Healthcare',
    price: 574.0,
    change: -2.5,
    changePercent: -0.43,
    ma50: 568.0,
    currentVolume: 2800000,
    weeklyAvgVolume: 2950000,
    pe: 28.4,
    low52w: 436.4,
    high52w: 606.4,
    marketCap: '$528B',
    dividendYield: 1.5,
    quantToGoStrategyId: 'retail_sentiment_reversal',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'XOM',
    name: 'Exxon Mobil Corp',
    quantToGoSymbol: 'NYSE:XOM',
    exchange: 'NYSE',
    market: 'US',
    currency: 'USD',
    sector: 'Energy',
    price: 122.4,
    change: -0.85,
    changePercent: -0.69,
    ma50: 118.5,
    currentVolume: 14200000,
    weeklyAvgVolume: 13900000,
    pe: 14.2,
    low52w: 95.8,
    high52w: 126.3,
    marketCap: '$488B',
    dividendYield: 3.2,
    quantToGoStrategyId: 'retail_sentiment_reversal',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
  {
    ticker: 'WMT',
    name: 'Walmart Inc',
    quantToGoSymbol: 'NYSE:WMT',
    exchange: 'NYSE',
    market: 'US',
    currency: 'USD',
    sector: 'Consumer Defensive',
    price: 81.25,
    change: 0.65,
    changePercent: 0.8,
    ma50: 77.8,
    currentVolume: 16500000,
    weeklyAvgVolume: 14800000,
    pe: 31.8,
    low52w: 51.5,
    high52w: 83.34,
    marketCap: '$654B',
    dividendYield: 1.0,
    quantToGoStrategyId: 'retail_sentiment_reversal',
    quantToGoUrl: 'https://github.com/QuantToGo/quanttogo-mcp',
  },
];

// Helper to look up a stock by standard ticker or QuantToGo symbol
export function findStockInUniverse(query: string): QuantToGoStockDefinition | undefined {
  const q = query.trim().toUpperCase();
  const normalized = q.replace(/^QTG:/, '').replace(/^STOCK:/, '');

  return QUANTTOGO_STOCK_UNIVERSE.find((s) => {
    return (
      s.ticker.toUpperCase() === normalized ||
      s.quantToGoSymbol.toUpperCase() === normalized ||
      s.quantToGoSymbol.toUpperCase() === `SGX:${normalized}` ||
      s.quantToGoSymbol.toUpperCase() === `NASDAQ:${normalized}` ||
      s.quantToGoSymbol.toUpperCase() === `NYSE:${normalized}` ||
      s.quantToGoSymbol.toUpperCase() === `HKG:${normalized}` ||
      s.quantToGoSymbol.toUpperCase() === `SHA:${normalized}` ||
      s.quantToGoSymbol.toUpperCase() === `SHE:${normalized}` ||
      s.name.toUpperCase().includes(normalized)
    );
  });
}
